### ISSUE TITLE
You asked for a code review...

### ISSUE THREAD

**Issue by davidjeddy** [dburiy/filecacher#2]
... saw your request for a code review on some social site and wanted to help out. Here are some suggestion / pointers / ideas to move the project forward.

- Lacking unit testing: This is a big one. 
- Code coverage: downstream consumers (people who will use your code) REALLY like seeing things like Lines of Code, quality metrics, and unit test coverage.

https://github.com/dburiy/filecacher/blob/master/src/FileCacher.php :

**line 8:**
```bash 
    private $mode;
```
Personally I would set the file mode to a very restrictive mode, then in __construct() override if provided. Convention over configuration, but allow custom configuration if desired.

**line 34:**
```bash
public function remove(string $key)
```
Not catch for failure of unlink(). I can think of a dozen reasons unlink() will failure. Let's capture this operation in a try/catch and return exeptions.

**line 217 and 224:***
```bash
@unlink($filename);
...
@rmdir($folder);
```
Using '@' suppresses errors, this is a bad practices. Capture, log, and handle errors.

**Overall**: PHP 7.0+ supports fn() return types.

**Comment by dburiy** [comment]
Thanks!
